
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: secrets.reader.secrets-store.csi.x-k8s.io
spec:
  group: reader.secrets-store.csi.x-k8s.io
  names:
    kind: Secret
    listKind: SecretList
    plural: secrets
    singular: secret
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Secret holds secret data of a certain type. The total bytes of
          the values in the Data field must be less than MaxSecretSize bytes.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          data:
            additionalProperties:
              format: byte
              type: string
            description: Data contains the secret data. Each key must consist of alphanumeric
              characters, '-', '_' or '.'. The serialized form of the secret data
              is a base64 encoded string, representing the arbitrary (possibly non-string)
              data value here. Described in https://tools.ietf.org/html/rfc4648#section-4
            type: object
          immutable:
            description: Immutable, if set to true, ensures that data stored in the
              Secret cannot be updated (only object metadata can be modified). If
              not set to true, the field can be modified at any time. Defaulted to
              nil.
            type: boolean
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          type:
            description: 'Used to facilitate programmatic handling of secret data.
              More info: https://kubernetes.io/docs/concepts/configuration/secret/#secret-types'
            type: string
        type: object
    served: true
    storage: true
